travis:
  secure:
    BINSTAR_TOKEN: WNzvK2w1Kk81DjVM4DYCYl9d2hodfjqeX7JTXDjCmSf99AnIm00pew8qDabm+Wwf13YcR38UvNZCaUhCLKBYMQR8L7xZm0ZE8/8bWCGdg3VLeneN7OLfWfII+FKnlsUYnclsl6VHf9wInFeOTv6yaRYSzPbS724lhThnsXbCMtKUWCqtJzaa/YzOP6FIIEMjBTf7m/UG/y/7DLGAsHFYmGeanclvBqViOI9hC6nnejnSLy6LqLt8d1CYElvb1GsHuIcWn/r83Fl9R1NekaCnscS4e69YEahTACd/ATZk7UuaPJigrdgtzuKQ3Tf91CJwRwpaZtOeoL8k9NvDPs+GA6r5PeJau4D8pN/UtnWQ5BHrpxu6XoCHmQcsNjiXXMmOule27S7MhCYnItA1ISvZXVZfbMfQI/T2hvRvuVrMdwtqOckPBkeJkromRtjb8Qv5SIdQW+gkOEEuzc61IJips110mMKjvsng/kOqQ0311VaxGFwCk0335/N/SJ1S2dIUpInK1mA2Hs7Q3x1KotNXkuEyaa/Q8LFubL2jVtFEmEDjYz+VFEUQY+/E/pTqisFi3+Pv8/aY+x+pbzUknJ3S1aRESFlvViR+UXr1Xfn8tIKyQEwUAyLWpWjXcYhl6ylI7w4a4dzFCJUz8o3wvPXSg6vUXltNJVWpLvwn4i1oYtY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
